version: 2
jobs:
  py-3.7: &build-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile" }}
      - run:
          name: Install dependencies
          command: |
            # install everything to run outside of pipenv
            pipenv lock --clear
            pipenv run conditional_install
      - run:
          name: Add Codecov
          command: | 
            pipenv install codecov
            pip install codecov --user
            /home/circleci/.local/bin/codecov
      - run:
          # Validate calls GUI code which fails if assistive_technologies are on
          name: Install dependencies for ODK Validate
          command: |
            sudo apt-get install -y openjdk-11-jre-headless
            sudo sed -i -e '/^assistive_technologies=/s/^/#/' /etc/java-*-openjdk/accessibility.properties
      - run:
          name: Test code is well formatted
          command: |
            if ! type /home/circleci/.local/bin/black > /dev/null; then
                echo "Black is not supported in this python version :("
            else
                /home/circleci/.local/bin/black --target-version=py27 pyxform --check --quiet || (echo 'The source code could use a bit more black.' && exit 1)
            fi
      - run:
          name: Run tests
          command: |
            pipenv run nosetests --with-coverage
            pipenv run nosetests --tests pyxform/tests_v1/ --with-coverage
      - run:
          name: upload coverage report
          command: |
            pipenv run coverage xml
            /home/circleci/.local/bin/codecov --required -X search gcov pycov -f coverage.xml
      - run:
          name: Building artifacts
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - store_artifacts:
          path: dist/
          destination: ./
      - save_cache:
          key: requirements-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile" }}
          paths:
            - /home/circleci/.local/lib
            - /home/circleci/.local/bin
  py-3.6:
    <<: *build-template
    docker:
      - image: circleci/python:3.6
  py-3.5:
    <<: *build-template
    docker:
      - image: circleci/python:3.5
  py-2.7:
    <<: *build-template
    docker:
      - image: circleci/python:2.7
workflows:
  version: 2
  build:
    jobs:
      - py-3.7
      - py-3.6
      - py-3.5
      - py-2.7
